# example values

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru

jsoup-connection-settings:
  userAgent: WondererSearchBot
  referrer: http://www.google.com

server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: shepardcmndr1992
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
